CREATE TABLE COMPUTADORA (
    IDCOMPUTADORA INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(20) not null,
    DESCRIPCION NVARCHAR(50) not null,
    PRECIO money not null,
    FECHAFABRICACION datetime not null,
	PRIMARY KEY (IDCOMPUTADORA),
);
SELECT * FROM COMPUTADORA